server:
  port: 9080
  servlet:
    context-path: /


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL配置
    driverClassName: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://gz-cynosdbmysql-grp-1rx89a8p.sql.tencentcdb.com:26140/db_edgeComputing?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    url: jdbc:mysql://gz-cynosdbmysql-grp-1rx89a8p.sql.tencentcdb.com:26140/db_bga?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
    username: root
    password: Mustang123456
#    url: jdbc:mysql://localhost:3306/db_edgeComputing?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true
#    username: root
#    password: mustang
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  web:
    resources:
      static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#指定数据库，可选值有【mysql、oracle、sqlserver、postgresql】
common:
  database: mysql